name: AsyncAPI Converter CI Pipeline

on:
  push:
    branches: [main]
    paths:
      - "node/async-api-converter/**"
  pull_request:
    branches: [main]
    paths:
      - "node/async-api-converter/**"
  workflow_dispatch:

jobs:
  setup-and-test:
    name: Tests (${{ matrix.os }}, Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x]

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.os }} ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install and Build
        run: npm ci
        working-directory: node/async-api-converter

      - name: Test
        timeout-minutes: 10
        run: npm run test
        working-directory: node/async-api-converter
