name: AAS AID CI Pipeline

on:
  push:
    branches: [main]
    paths:
      - "node/aas-aid/**"
  pull_request:
    branches: [main]
    paths:
      - "node/aas-aid/**"
  workflow_dispatch:

jobs:
  setup-and-test:
    name: Tests (${{ matrix.os }}, Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x]

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.os }} ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install
        run: npm ci
        working-directory: node/aas-aid

      - name: Build
        run: npm run build
        working-directory: node/aas-aid

      - name: Test
        timeout-minutes: 10
        run: npm run test
        working-directory: node/aas-aid
# TODO: need to decide how to deal with linting and prettier
#
#  eslint:
#    name: eslint
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Use Node.js 18
#        uses: actions/setup-node@v1
#        with:
#          node-version: 18
#
#      - name: Install
#        run: npm ci
#
#      - name: Lint
#        run: npm run lint
#
#  prettier:
#    name: Check coding style
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actionsx/prettier@v2
#        with:
#          args: --check .
