on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  upload-to-codecov:
    name: Upload Test Results to Codecov
    runs-on: ubuntu-latest

    steps:
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
          verbose: true
